builds:
  -
    binary: docker-machine-driver-vmware
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  format: binary
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
changelog:
  filters:
    exclude:
      - '^typo'
      - 'version bump'