language: go
os: 
  - linux
  - osx

go:
  - 1.14.x
  - '1.14.2'
go_import_path: github.com/machine-drivers/docker-machine-driver-vmware

install:
  - echo "Don't run anything."
script:
  - make test

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    go: '1.14.2'