name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make GOARCH=amd64 GOOS=windows
      
    - name: Upload release
      uses: yakuhzi/action-release@v1
      with:
        file: out/docker-machine-driver-vmware.exe
